# configs
BOT_PREFIX="p!"

# constants
GREEN_CHECKMARK_EMOJI="\u2705"
RED_CROSS_EMOJI="\u274c"
BLUE_BALL_EMOJI="\U0001F535"
BLACK_BALL_EMOJI="\u26ab"
PURPLE_BALL_EMOJI="\U0001F7E3"
BROWN_BALL_EMOJI="\U0001F7E4"
GREEN_BALL_EMOJI="\U0001F7E2"
YELLOW_BALL_EMOJI="\U0001F7E1"
ORANGE_BALL_EMOJI="\U0001F7E0"
WHITE_BALL_EMOJI="\u26aa"

# styles
QUEUE_DECORATORS = [
    BLUE_BALL_EMOJI, BLACK_BALL_EMOJI, PURPLE_BALL_EMOJI, 
    BROWN_BALL_EMOJI, GREEN_BALL_EMOJI, YELLOW_BALL_EMOJI, 
    ORANGE_BALL_EMOJI, WHITE_BALL_EMOJI
]
