# configs
BOT_PREFIX="p!"

# constants
PLAY_PAUSE_EMOJI="\u23ef\ufe0f"
LAST_TRACK_EMOJI="\u23ee\ufe0f"
NEXT_TRACK_EMOJI="\u23ed\ufe0f"
SHUFFLE_EMOJI="\U0001F500"
NEW_BUTTON_EMOJI="\U0001F195"
REPEAT_ONE_EMOJI="\U0001F502"
GREEN_CHECKMARK_EMOJI="\u2705"
RED_CROSS_EMOJI="\u274c"
BLUE_BALL_EMOJI="\U0001F535"
BLACK_BALL_EMOJI="\u26ab"
PURPLE_BALL_EMOJI="\U0001F7E3"
BROWN_BALL_EMOJI="\U0001F7E4"
GREEN_BALL_EMOJI="\U0001F7E2"
YELLOW_BALL_EMOJI="\U0001F7E1"
ORANGE_BALL_EMOJI="\U0001F7E0"
WHITE_BALL_EMOJI="\u26aa"

# styles
QUEUE_DECORATORS = [
    BLUE_BALL_EMOJI, BLACK_BALL_EMOJI, PURPLE_BALL_EMOJI, 
    BROWN_BALL_EMOJI, GREEN_BALL_EMOJI, YELLOW_BALL_EMOJI, 
    ORANGE_BALL_EMOJI, WHITE_BALL_EMOJI
]

AV_EMOJIS = {
    'play': PLAY_PAUSE_EMOJI,
    'last_track': LAST_TRACK_EMOJI,
    'next_track': NEXT_TRACK_EMOJI,
    'shuffle': SHUFFLE_EMOJI,
    'autoplay': NEW_BUTTON_EMOJI,
    'repeat_one': REPEAT_ONE_EMOJI
}
