version: "3.8"
services:
  penguintunes:
    restart: unless-stopped
    build:
      context: .
    environment:
        TOKEN: ${DISCORD_TOKEN}
        LAVALINK_SERVER_PASSWORD: ${LAVALINK_SERVER_PASSWORD}
        LAVALINK_SERVER_HOST: ${LAVALINK_SERVER_HOST}
        LAVALINK_SERVER_PORT: ${LAVALINK_SERVER_PORT}
    depends_on: 
      - lavalink
    networks:
      - lavalink
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/:rw
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"
networks:
  lavalink:
    name: lavalink