version: "3.8"
services:
  penguintunes:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        TOKEN: ${DISCORD_TOKEN}
        LAVALINK_SERVER_PASSWORD: ${LAVALINK_SERVER_PASSWORD}
        LAVALINK_SERVER_HOST: ${LAVALINK_SERVER_HOST}
        LAVALINK_SERVER_PORT: ${LAVALINK_SERVER_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        DB_HOST: "mysql"
        DB_PORT: "3306"
        BOT_OWNER_ID: ${BOT_OWNER_ID}
    depends_on: 
      - lavalink
      - mysql
    networks:
      - lavalink
      - mysql

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/:rw
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

  mysql:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - mysql

  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - lavalink
      - mysql

volumes:
  data:

networks:
  lavalink:
    name: lavalink
  mysql:
    name: mysql
