version: "3.8"
services:
  piplup:
    restart: unless-stopped
    build:
      context: .
      args:
        TOKEN: ${DISCORD_TOKEN}
        LAVALINK_SERVER_PASSWORD: ${LAVALINK_SERVER_PASSWORD}
    depends_on: 
      - lavalink
    networks:
      - lavalink
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"
networks:
  lavalink:
    name: lavalink