version: "3.8"
services:
  penguintunes:
    restart: unless-stopped
    build:
      context: .
    environment:
        TOKEN: ${DISCORD_TOKEN}
        LAVALINK_SERVER_PASSWORD: ${LAVALINK_SERVER_PASSWORD}
        LAVALINK_SERVER_HOST: ${LAVALINK_SERVER_HOST}
        LAVALINK_SERVER_PORT: ${LAVALINK_SERVER_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        DB_HOST: "dbpostgres"
        DB_PORT: "5432"
        BOT_OWNER_ID: ${BOT_OWNER_ID}
    depends_on: 
      - lavalink
      - dbpostgres
    networks:
      - lavalink
      - dbpostgres
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/:rw
    networks:
      - lavalink
    expose:
      - 2333
  dbpostgres:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - dbpostgres
networks:
  lavalink:
    name: lavalink
  dbpostgres:
    name: dbpostgres